import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteLoader from "./components/Loader/RouteLoader";
import LayoutWrapper from "./components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Biginity',
  description: 'Generated by Next.js',
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <RouteLoader>
          <LayoutWrapper>{children}</LayoutWrapper>
        </RouteLoader>
      </body>
    </html>
  );
}
