// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✅ Wrap UI with ClientOnly
import { SocketProvider } from "../lib/api/initSocket";
import ClientOnly from "./components/ClientOnly";
import ShowNavbar from "./components/ShowNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Biginity",
  description: "Generated by Next.js",
  icons: { icon: "/logo.png" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <ClientOnly>
          <SocketProvider>
            <ShowNavbar></ShowNavbar>
            {children}
          </SocketProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
